{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "filters", "default": null, "conditions": [], "min_value": 4, "max_value": 16, "step": 4, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "normalization_type", "default": "instance", "conditions": [], "values": ["instance", "batch"], "ordered": false}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 1e-06, "conditions": [], "min_value": 1e-06, "max_value": 0.0001, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "augmentation_level", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "batch_size", "default": 5, "conditions": [], "values": [5, 10], "ordered": true}}], "values": {"filters": 16, "dropout_rate": 0.5, "normalization_type": "instance", "learning_rate": 1.9108895538608297e-05, "augmentation_level": 5, "batch_size": 5, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 7, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/l.peiwang/liuenv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/l.peiwang/liuenv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/sat_model.py\", line 141, in run_trial\n    model.fit(train_data_gen, epochs=kwargs['epochs'], validation_data=val_data_gen)\n  File \"/home/l.peiwang/liuenv/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 67, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/sat_model.py\", line 108, in __len__\n    return np.ceil(len(self.images) / self.batch_size).astype(np.int)\n  File \"/home/l.peiwang/liuenv/lib/python3.10/site-packages/numpy/__init__.py\", line 324, in __getattr__\n    raise AttributeError(__former_attrs__[attr])\nAttributeError: module 'numpy' has no attribute 'int'.\n`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.\nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n"}